version: "3.3"
services:
  ccore-api:
    image: obdpy_core_api:1.0
    container_name: obdpy_core_api
    build:
      dockerfile: ./dockerfile
    restart: always
    environment:
      - DB_HOST=obd-dev.sensorid.it
      - DB_PORT=27017
      - DB_USER=sensoridAdmin
      - DB_PASSWD=10T53nsor.2010!
      - APP_HOST=0.0.0.0
      - APP_PORT=8010
    volumes:
      - /home/sensorid/apps/libs:/apps
    #depends_on:
    #  - mqtt-broker
    ports:
      - "8010:8010"